FROM golang:1.22.1 as builder

WORKDIR /app

COPY go.mod go.mod
# COPY go.sum go.sum
# RUN go mod download

COPY cmd/ cmd/
COPY app/ app/
COPY data/ data/
COPY internal/ internal/

CMD ["go", "test", "./...", "-count=1", "-v"]
