#!/usr/bin/env bash

region="$AWS_REGION"
profile="$AWS_PROFILE"
aws_user_id="743193056723"

image_name="redocker"
repo="redocker"
tag="latest"

aws ecr get-login-password --region $region --profile $profile | docker login --username AWS --password-stdin $aws_user_id.dkr.ecr.$region.amazonaws.com
docker tag $image_name $aws_user_id.dkr.ecr.$region.amazonaws.com/$repo:$tag
docker push $aws_user_id.dkr.ecr.$region.amazonaws.com/$repo:$tag